import assert from "node:assert/strict";
import test from "node:test";
import { CATEGORIES } from "../src/model.js";
import { scanSource } from "../src/scanner.js";

test("scanner detects comments and preserves source ranges", () => {
  const findings = scanSource('const value = "// literal"; // actual\n/// docs\n', "fixture.js", "javascript", new Set([CATEGORIES.ORDINARY, CATEGORIES.DOCUMENTATION]));
  assert.equal(findings.length, 2);
  assert.equal(findings[0].text, "// actual");
  assert.deepEqual(findings[0].range.start, { line: 1, column: 29 });
  assert.equal(findings[1].category, CATEGORIES.DOCUMENTATION);
});

test("scanner handles representative language delimiters and category filters", () => {
  assert.equal(scanSource("value = 1 # actual\n", "fixture.py", "python").length, 1);
  assert.equal(scanSource("SELECT 1; -- actual\n", "fixture.sql", "sql").length, 1);
  assert.equal(scanSource("<!-- actual -->\n", "fixture.html", "html").length, 1);
  assert.equal(scanSource("// generated by tool\n", "fixture.js", "javascript", new Set([CATEGORIES.ORDINARY])).length, 0);
  assert.equal(scanSource("// generated by tool\n", "fixture.js", "javascript", new Set([CATEGORIES.HEADER])).length, 1);
});
