version: 2

dist: .goreleaser-dist

project_name: ban-code-comments

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: ban-code-comments
    main: ./cmd/ban-code-comments
    binary: ban-code-comments
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    ids:
      - ban-code-comments
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
