package scanner

import (
	"bytes"
	"strings"
	"unicode"

	"github.com/JustinDFuller/ban-code-comments/internal/model"
)

type blockDelimiter struct {
	start string
	end   string
}

type syntax struct {
	line      []string
	block     []blockDelimiter
	nested    bool
	heredoc   bool
	rubyBlock bool
}

func Scan(path string, language model.Language, source []byte, selected map[model.Category]bool) []model.Finding {
	spec, ok := syntaxFor(language)
	if !ok {
		return nil
	}
	findings := make([]model.Finding, 0)
	for index := 0; index < len(source); {
		if spec.heredoc && atLineStart(source, index) {
			if end, found := skipShellHeredoc(source, index); found {
				index = end
				continue
			}
		}
		if spec.rubyBlock && atLineStart(source, index) && bytes.HasPrefix(source[index:], []byte("=begin")) {
			if end := findRubyBlockEnd(source, index); end > index {
				appendFinding(&findings, path, language, source, index, end, selected)
				index = end
				continue
			}
		}
		if end, found := skipString(source, index); found {
			index = end
			continue
		}
		matched := false
		for _, delimiter := range spec.block {
			if !bytes.HasPrefix(source[index:], []byte(delimiter.start)) {
				continue
			}
			end := findBlockEnd(source, index+len(delimiter.start), delimiter, spec.nested)
			appendFinding(&findings, path, language, source, index, end, selected)
			index = end
			matched = true
			break
		}
		if matched {
			continue
		}
		for _, delimiter := range spec.line {
			if !bytes.HasPrefix(source[index:], []byte(delimiter)) {
				continue
			}
			end := index + bytes.IndexByte(source[index:], '\n')
			if end < index {
				end = len(source)
			}
			appendFinding(&findings, path, language, source, index, end, selected)
			index = end
			matched = true
			break
		}
		if matched {
			continue
		}
		index++
	}
	return findings
}

func syntaxFor(language model.Language) (syntax, bool) {
	cStyle := syntax{line: []string{"//"}, block: []blockDelimiter{{start: "/*", end: "*/"}}}
	switch language {
	case "go", "javascript", "typescript", "java", "c", "cpp", "csharp", "kotlin", "swift", "rust", "jsonc":
		cStyle.nested = language == "rust"
		return cStyle, true
	case "python":
		return syntax{line: []string{"#"}}, true
	case "ruby":
		return syntax{line: []string{"#"}, rubyBlock: true}, true
	case "php":
		return syntax{line: []string{"//", "#"}, block: []blockDelimiter{{start: "/*", end: "*/"}}}, true
	case "shell", "yaml", "toml", "dockerfile", "makefile":
		return syntax{line: []string{"#"}, heredoc: language == "shell"}, true
	case "ini":
		return syntax{line: []string{"#", ";"}}, true
	case "sql":
		return syntax{line: []string{"--", "#"}, block: []blockDelimiter{{start: "/*", end: "*/"}}}, true
	case "html", "xml":
		return syntax{block: []blockDelimiter{{start: "<!--", end: "-->"}}}, true
	case "css":
		return syntax{block: []blockDelimiter{{start: "/*", end: "*/"}}}, true
	case "scss":
		return syntax{line: []string{"//"}, block: []blockDelimiter{{start: "/*", end: "*/"}}}, true
	case "hcl", "terraform":
		return syntax{line: []string{"#", "//"}, block: []blockDelimiter{{start: "/*", end: "*/"}}}, true
	case "json":
		return syntax{}, true
	default:
		return syntax{}, false
	}
}

func appendFinding(findings *[]model.Finding, path string, language model.Language, source []byte, start, end int, selected map[model.Category]bool) {
	if end <= start {
		return
	}
	text := string(source[start:end])
	category := classify(text)
	if len(selected) > 0 && !selected[category] {
		return
	}
	*findings = append(*findings, model.Finding{Path: path, Language: language, Category: category, Range: model.Range{Start: positionAt(source, start), End: positionAt(source, end)}, Text: text})
}

func classify(text string) model.Category {
	trimmed := strings.TrimSpace(text)
	lower := strings.ToLower(trimmed)
	if strings.HasPrefix(trimmed, "///") || strings.HasPrefix(trimmed, "//!") || strings.HasPrefix(trimmed, "/**") {
		return model.CategoryDocumentation
	}
	for _, marker := range []string{"go:", "cgo", "eslint", "ts-ignore", "ts-expect-error", "prettier-ignore", "nolint", "noinspection", "shellcheck", "yamllint", "yaml-language-server", "coding:", "type: ignore", "swift-tools-version", "region", "endregion"} {
		if strings.Contains(lower, marker) {
			return model.CategoryDirective
		}
	}
	for _, marker := range []string{"copyright", "spdx-license", "licensed", "license", "generated by", "code generated", "auto-generated"} {
		if strings.Contains(lower, marker) {
			return model.CategoryHeader
		}
	}
	return model.CategoryOrdinary
}

func skipString(source []byte, index int) (int, bool) {
	quoteIndex := index
	raw := false
	if index < len(source) && (source[index] == 'r' || source[index] == 'R' || source[index] == 'f' || source[index] == 'F' || source[index] == 'u' || source[index] == 'b' || source[index] == 'U' || source[index] == 'B') && index+1 < len(source) {
		if source[index+1] == '"' || source[index+1] == '\'' {
			quoteIndex = index + 1
			raw = source[index] == 'r' || source[index] == 'R'
		} else if source[index+1] == '#' {
			quoteIndex = index + 1
			for quoteIndex < len(source) && source[quoteIndex] == '#' {
				quoteIndex++
			}
			if quoteIndex >= len(source) || source[quoteIndex] != '"' {
				return 0, false
			}
			raw = true
		}
	}
	if quoteIndex >= len(source) || (source[quoteIndex] != '\'' && source[quoteIndex] != '"' && source[quoteIndex] != '`') {
		return 0, false
	}
	quote := source[quoteIndex]
	if quote == '`' {
		if end := bytes.IndexByte(source[quoteIndex+1:], '`'); end >= 0 {
			return quoteIndex + 2 + end, true
		}
		return len(source), true
	}
	triple := quoteIndex+2 < len(source) && source[quoteIndex+1] == quote && source[quoteIndex+2] == quote
	if triple {
		end := bytes.Index(source[quoteIndex+3:], []byte{quote, quote, quote})
		if end < 0 {
			return len(source), true
		}
		return quoteIndex + 6 + end, true
	}
	if raw {
		if end := bytes.IndexByte(source[quoteIndex+1:], quote); end >= 0 {
			return quoteIndex + 2 + end, true
		}
		return len(source), true
	}
	for cursor := quoteIndex + 1; cursor < len(source); cursor++ {
		if source[cursor] == '\\' {
			cursor++
			continue
		}
		if source[cursor] == quote {
			return cursor + 1, true
		}
		if source[cursor] == '\n' && quote != '`' {
			return cursor, true
		}
	}
	return len(source), true
}

func findBlockEnd(source []byte, contentStart int, delimiter blockDelimiter, nested bool) int {
	depth := 1
	for index := contentStart; index < len(source); {
		if nested && bytes.HasPrefix(source[index:], []byte(delimiter.start)) {
			depth++
			index += len(delimiter.start)
			continue
		}
		if bytes.HasPrefix(source[index:], []byte(delimiter.end)) {
			depth--
			index += len(delimiter.end)
			if depth == 0 {
				return index
			}
			continue
		}
		index++
	}
	return len(source)
}

func skipShellHeredoc(source []byte, index int) (int, bool) {
	lineEnd := bytes.IndexByte(source[index:], '\n')
	if lineEnd < 0 {
		lineEnd = len(source) - index
	}
	line := source[index : index+lineEnd]
	marker := bytes.Index(line, []byte("<<"))
	if marker < 0 {
		return 0, false
	}
	marker += 2
	if marker < len(line) && line[marker] == '-' {
		marker++
	}
	for marker < len(line) && (line[marker] == ' ' || line[marker] == '\t') {
		marker++
	}
	start := marker
	for marker < len(line) && (unicode.IsLetter(rune(line[marker])) || unicode.IsDigit(rune(line[marker])) || line[marker] == '_') {
		marker++
	}
	if marker == start {
		return 0, false
	}
	terminator := string(line[start:marker])
	search := index + lineEnd
	if search < len(source) {
		search++
	}
	for search < len(source) {
		end := bytes.IndexByte(source[search:], '\n')
		if end < 0 {
			end = len(source) - search
		}
		candidate := strings.TrimSpace(string(source[search : search+end]))
		if candidate == terminator {
			endIndex := search + end
			if endIndex < len(source) {
				endIndex++
			}
			return endIndex, true
		}
		search += end
		if search < len(source) {
			search++
		}
	}
	return len(source), true
}

func findRubyBlockEnd(source []byte, index int) int {
	search := index
	for search < len(source) {
		lineEnd := bytes.IndexByte(source[search:], '\n')
		if lineEnd < 0 {
			lineEnd = len(source) - search
		}
		if search > index && bytes.HasPrefix(bytes.TrimSpace(source[search:search+lineEnd]), []byte("=end")) {
			end := search + lineEnd
			if end < len(source) {
				end++
			}
			return end
		}
		search += lineEnd
		if search < len(source) {
			search++
		}
	}
	return len(source)
}

func atLineStart(source []byte, index int) bool {
	return index == 0 || source[index-1] == '\n'
}

func positionAt(source []byte, offset int) model.Position {
	line, column := 1, 1
	for index := 0; index < offset && index < len(source); index++ {
		if source[index] == '\n' {
			line++
			column = 1
		} else {
			column++
		}
	}
	return model.Position{Line: line, Column: column}
}
