import { CATEGORIES, finding, position, sourceRange } from "./model.js";

const syntax = {
  c: { line: ["//"], block: [["/*", "*/"]] }, cpp: { line: ["//"], block: [["/*", "*/"]] }, csharp: { line: ["//"], block: [["/*", "*/"]] },
  go: { line: ["//"], block: [["/*", "*/"]] }, java: { line: ["//"], block: [["/*", "*/"]] }, javascript: { line: ["//"], block: [["/*", "*/"]] },
  jsonc: { line: ["//"], block: [["/*", "*/"]] }, kotlin: { line: ["//"], block: [["/*", "*/"]] }, rust: { line: ["//"], block: [["/*", "*/"]] }, swift: { line: ["//"], block: [["/*", "*/"]] },
  typescript: { line: ["//"], block: [["/*", "*/"]] }, php: { line: ["//", "#"], block: [["/*", "*/"]] },
  python: { line: ["#"] }, ruby: { line: ["#"] }, shell: { line: ["#"] }, yaml: { line: ["#"] }, toml: { line: ["#"] }, dockerfile: { line: ["#"] }, makefile: { line: ["#"] },
  ini: { line: ["#", ";"] }, sql: { line: ["--", "#"], block: [["/*", "*/"]] }, html: { block: [["<!--", "-->"]] }, xml: { block: [["<!--", "-->"]] },
  css: { block: [["/*", "*/"]] }, scss: { line: ["//"], block: [["/*", "*/"]] }, hcl: { line: ["#", "//"], block: [["/*", "*/"]] }, terraform: { line: ["#", "//"], block: [["/*", "*/"]] },
  json: { line: [], block: [] },
};

function lineColumn(source, offset) {
  const prefix = source.slice(0, offset);
  const line = (prefix.match(/\n/g) || []).length + 1;
  const lastBreak = Math.max(prefix.lastIndexOf("\n"), prefix.lastIndexOf("\r"));
  return position(line, offset - lastBreak);
}

function escaped(source, offset) {
  let count = 0;
  for (let index = offset - 1; index >= 0 && source[index] === "\\"; index -= 1) count += 1;
  return count % 2 === 1;
}

function classify(text) {
  const trimmed = text.trim();
  const lower = trimmed.toLowerCase();
  if (trimmed.startsWith("///") || trimmed.startsWith("//!") || trimmed.startsWith("/**") || trimmed.startsWith("<!---")) return CATEGORIES.DOCUMENTATION;
  if (trimmed.startsWith("#!") || lower.startsWith("# syntax=") || lower.startsWith("# escape=")) return CATEGORIES.DIRECTIVE;
  if (["go:", "cgo", "eslint", "ts-ignore", "ts-expect-error", "prettier-ignore", "nolint", "noinspection", "shellcheck", "yamllint", "yaml-language-server", "coding:", "type: ignore", "swift-tools-version", "region", "endregion"].some((marker) => lower.includes(marker))) return CATEGORIES.DIRECTIVE;
  if (["copyright", "spdx-license", "licensed", "license", "generated by", "code generated", "auto-generated"].some((marker) => lower.includes(marker))) return CATEGORIES.HEADER;
  return CATEGORIES.ORDINARY;
}

function addFinding(findings, source, filePath, language, start, end, categories) {
  const text = source.slice(start, end).replace(/[\r\n]+$/, "");
  if (!text) return;
  const category = classify(text);
  if (!categories.has(category)) return;
  findings.push(finding(filePath, language, category, sourceRange(lineColumn(source, start), lineColumn(source, start + text.length)), text));
}

function skipQuoted(source, index, quote) {
  for (let cursor = index + quote.length; cursor < source.length; cursor += 1) {
    if (source.startsWith(quote, cursor) && !escaped(source, cursor)) return cursor + quote.length;
    if (source[cursor] === "\n" && quote !== "`" && quote !== "'''" && quote !== '"""') return cursor;
  }
  return source.length;
}

function stringAt(source, index, language) {
  for (const quote of ["'''", '"""']) if (source.startsWith(quote, index)) return skipQuoted(source, index, quote);
  if (language === "csharp" && (source.startsWith('@"', index) || source.startsWith('$@"', index) || source.startsWith('@$"', index))) return skipQuoted(source, index + (source[index] === "$" ? 2 : 1), '"');
  if (language === "rust" && /r#+"/.test(source.slice(index, index + 12))) {
    const match = source.slice(index).match(/^r(#+)"/); if (match) { const close = `"${match[1]}`; const end = source.indexOf(close, index + match[0].length); return end < 0 ? source.length : end + close.length; }
  }
  if (language === "javascript" || language === "typescript") {
    if (source[index] === "`" || source[index] === '"' || source[index] === "'") return skipQuoted(source, index, source[index]);
  }
  if (source[index] === '"' || source[index] === "'") return skipQuoted(source, index, source[index]);
  return null;
}

export function scanSource(source, filePath = "<text>", language, categories = new Set([CATEGORIES.ORDINARY, CATEGORIES.DOCUMENTATION])) {
  const spec = syntax[language];
  if (!spec) return [];
  const findings = [];
  let index = 0;
  while (index < source.length) {
    const stringEnd = stringAt(source, index, language);
    if (stringEnd !== null) { index = stringEnd; continue; }
    let matched = false;
    for (const [start, endMarker] of spec.block || []) if (source.startsWith(start, index)) {
      const end = source.indexOf(endMarker, index + start.length);
      addFinding(findings, source, filePath, language, index, end < 0 ? source.length : end + endMarker.length, categories);
      index = end < 0 ? source.length : end + endMarker.length; matched = true; break;
    }
    if (matched) continue;
    for (const marker of spec.line || []) if (source.startsWith(marker, index)) {
      const previous = source[index - 1];
      if ((language === "shell" || language === "yaml") && marker === "#" && previous && !/[\s;]/.test(previous)) continue;
      if (language === "sql" && marker === "#" && [">", "<", "-"].includes(previous)) continue;
      const newline = source.slice(index).search(/[\r\n]/);
      addFinding(findings, source, filePath, language, index, newline < 0 ? source.length : index + newline, categories);
      index = newline < 0 ? source.length : index + newline; matched = true; break;
    }
    if (!matched) index += 1;
  }
  return findings;
}

export { classify, lineColumn, syntax };
